//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcGarage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int CardId { get; set; }
        public int MemberId { get; set; }
        public string NameOnCard { get; set; }
        public int CardNumber { get; set; }
        public int CVC { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
